[package]
name = "minigit"
version = "0.1.0"
authors = ["Wafelack <wafelack@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.21"
anyhow = "1.0.43"
chrono = "0.4.19"
structopt = "0.3.22"
